title: Better Continents Guide
description: "Guide for Better Continents Valheim mod"
remote_theme: pmarsceill/just-the-docs@v0.2.9


# Theme settings:
color_scheme: "dark"
logo: ''

# Aux links for the upper right navigation
aux_links:
  "Nexusmods page":
    - "https://www.nexusmods.com/valheim/mods/446"
  "Discord":
    - "https://discord.gg/3XW8ZntYzN"
  "GitHub Page":
    - "https://github.com/billw2012/BetterContinents"

# Footer content appears at the bottom of every page's main content
footer_content: ''

search_enabled: true

# Footer metadata
show_last_edit_time: true
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
show_gh_edit_link: true
gh_edit_repository: "https://github.com/billw2012/BetterContinents-Docs" # the github URL for your repo
gh_edit_branch: "master/docs" # switch to the branch that your docs is served from
gh_edit_view_mode: "edit" # switch to "edit" if you want the user to jump into the editor immediately
edit_link_text: "Edit this page on GitHub."
